### ISSUE TITLE
Pressing delete passed content defaults as back button

### ISSUE THREAD

**Issue by CoreyTrombley** [bmcmahen/react-wysiwyg#18]
While holding the delete button I was sent back to a empty tab.

Here is my example code that I was using:

```
var InlineEdit = require('react-wysiwyg');

var HeaderBrandDetail = React.createClass({
  displayName: 'HeaderBrandDetail',
  propTypes: {
    resourceDetail: React.PropTypes.object.isRequired
  },

  getInitialState: function() {
    return {
      text: '',
      editing: false
    };
  },

  enableEditing: function(){
    // contenteditable field set to edit mode.
    this.setState({ editing: true });
  },

  render: function() {

    return (
      <HeaderDetail>

                 ...
                  <InlineEdit text={this.props.resourceDetail.detail.name || 'hello'}
                              onChange={function(){console.log('changed')}}
                              onEnterKey={function(){console.log('enter pressed')}}
                              onEscapekey={function(){console.log('escape pressed')}}
                              autoFocus={true}
                              editing={this.state.editing}
                  />
                  <span onClick={this.enableEditing} className="fa fa-pencil hidden-xs"></span>
                  ...

      </HeaderDetail>
    );

  }
});

module.exports = HeaderBrandDetail;
```

![weird](https://cloud.githubusercontent.com/assets/2028391/9261469/04171494-41dc-11e5-935d-bd2881ab673a.gif)

**Comment by bmcmahen** [comment]
Hmm. So this occurs when pressing `delete` without setting a placeholder attribute? Let me look into it...

**Comment by bmcmahen** [comment]
Also, which version of this are you using? The api looks old...

**Comment by CoreyTrombley** [comment]
Hey Ben on the move atm. But I just did npm install that was in your Readme

**Comment by bmcmahen** [comment]
okay, looking into it regardless. thanks for the bug report

**Comment by bmcmahen** [comment]
I'm fairly confident this issue has been resolved in recent releases of this module. Please make sure that you are running the latest version `2.0.4` and that your usage looks like that in the current readme / examples. I'm going to close this for now, but if you continue to have issues, let me know.
