### ISSUE TITLE
Steal focus ?

### ISSUE THREAD

**Issue by amigrave** [bmcmahen/react-wysiwyg#25]
Hi,

Is there a way to prevent the ContentEditable component to steal focus on rendering ?

**Comment by bmcmahen** [comment]
Hmm, I haven't noticed this behaviour myself. Can you give me some more details or example code?

**Comment by amigrave** [comment]
This happens when you change the content editable's content from another component but I guess this use case is out of concern. In my case I used`shouldComponentUpdate` in order to prevent this behavior.
