### ISSUE TITLE
Avoid built-in style hotkeys

### ISSUE THREAD

**Issue by syranide** [bmcmahen/react-wysiwyg#30]
ctrl-b, ctrl-u, etc applies styling to the selected text, but disappears when the next change event is emitted (naturally). Can these be disabled/detected somehow?

**Comment by bmcmahen** [comment]
Are you using the `preventStyling` prop?

**Comment by syranide** [comment]
@bmcmahen I tried it on your example project (and it's using `preventStyling` as far as I can tell).

**Comment by syranide** [comment]
It seems you're only testing for the Meta-key (Mac) and not the Control-key (PC)... however, is this a safe way of doing it? Aren't these mapped to other keys in other languages/browsers?

**Comment by bmcmahen** [comment]
Hmm, I had assumed that `e.metaKey` would be normalized by React to include command and control keys on their respective platform, but I don't think I've actually tested this. At any rate, this would be an easy fix. Not sure when I'll get to it... but would gladly accept a PR.
