### ISSUE TITLE
Remove Editable Button

### ISSUE THREAD

**Issue by JGSolutions** [bmcmahen/react-wysiwyg#7]
Is there a way that the user can click or tap on the text and switches to the editable field instead of have a button to make it editable?

**Comment by bmcmahen** [comment]
Yeah, you could do something like that fairly easily. Just wrap the field in a div and listen for an onClick event handler. When the user clicks (or double clicks) the div, set the editing state to `true`. This will then transition the field into the editing mode.

**Comment by JGSolutions** [comment]
Ok i can try that. Can i do an onBlur? If the user exits the div it disables the field?

**Comment by bmcmahen** [comment]
I think so -- I haven't actually tried this myself, but I suspect it would work. Let me know how it goes.
